Quick fixes for an upcoming version of rustc
No functional changes intended.

1. Relaxed some rustc::internal due to new internal lints such as:
```
error: usage of `ty::TyKind::<kind>`
  --> third_party/crubit/cc_bindings_from_rs/generate_bindings/query_compiler.rs:41:9
   |
41 |         ty::TyKind::Bool
   |         ^^^^^^^^^^ help: try using `ty::<kind>` directly: `ty`
   |
note: the lint level is defined here
  --> third_party/crubit/cc_bindings_from_rs/generate_bindings/query_compiler.rs:5:9
   |
 5 | #![deny(rustc::internal)]
   |         ^^^^^^^^^^^^^^^
   = note: `#[deny(rustc::usage_of_ty_tykind)]` implied by `#[deny(rustc::internal)]`
error: prefer `FxHashMap` over `HashMap`, it has better performance
```

2. The (equivalent of) -Zunstable-options is now needed when building with a target json

PiperOrigin-RevId: 868642654