Allow function pointers with references inside the function signature.
Without this change, because we change the reference to a pointer, the type doesn't line up:

```
error: cannot initialize return object of type 'crubit::t
ype_identity_t<int *(const int *, int *)> *' (aka 'int *(*)(const int *, int *)') with an rvalue of type 'int &(*)(const int &, int *)': type mismatch at 1st parameter
('const int *' vs 'const int &')
```

I was worried this would mean we'd have trouble with `-Wreturn-type-c-linkage`, but surprisingly, it works fine:

https://godbolt.org/z/njabjEfTK

(As you can see, and as the name implies, it also works fine with reference parameters, but presumably there's another warning that fails there.)

I didn't add any other tests because really "does it compile?" is the main thing. This failed before, succeeds now.

PiperOrigin-RevId: 478958712