Mark `SomeStruct` which is passed across FFI boundary as `#[repr(C)]`
This avoids the warning (hence test failure):

```
error: `extern` fn uses type `SomeStruct`, which is not FFI-safe
 --> <crubit_unittests.rs>:1:592
  |
1 | ...tOfStruct ; pub fn test_function (_arg : extern "C" fn (SomeStruct , f32) -> f32) { unimplemented ! () }
  |                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not FFI-safe
  |
  = help: consider adding a `#[repr(C)]` or `#[repr(transparent)]` attribute to this struct
  = note: this struct has unspecified layout
note: the type is defined here
```
PiperOrigin-RevId: 546911383
Change-Id: I6ec0bb387a16de33af841e2b3c551a5ded6709b0