Support 32-bit target architectures in the `ffi_11` crate.
Before this CL, targeting a 32-bit architecture could hit a build error
like the one below:

```
error[E0432]: unresolved import `long_integers`
   --> third_party/crubit/support/ffi_11/src/lib.rs:361:9
    |
361 | pub use long_integers::new_c_long;
    |         ^^^^^^^^^^^^^ use of unresolved module or unlinked crate `long_integers`
```

That error was caused by the fact that before this CL the
`mod long_integers` module was only defined for 64-bit architectures.

This CL also extends `build_test` coverage to `crubit_rust_test` to help
verify that the new `mod long_integers` uses the correct Rust types.  I have
verified that using `u64` instead of `i32` would fail the following build:

PiperOrigin-RevId: 930099471