Check for `CRUBIT_MUST_BIND` before discarding `private` items.
Also, while I'm here, give a hard error for `CRUBIT_MUST_BIND` + `CRUBIT_DO_NOT_BIND`.

The goal being, then, that after this CL, `CRUBIT_MUST_BIND` -> if bindings generation succeeded, this declaration has bindings. And `CRUBIT_DO_NOT_BIND` -> if bindings generation succeeded, this declaration does not have bindings.

There may be other cases, but I think this should be most of it. The declaration importer is the only place where we can have this problem (because it can skip items entirely), and it now does the check at every conditional in the importer's main function.

Tested manually, gives an error as so:

```c++
struct TwoWords {
  void* ptr1;
  void* ptr2;
  private: CRUBIT_MUST_BIND void foo() {}
};
```

->

```
error: function `unique_ptr_test::TwoWords::foo` could not be bound
  Private declarations cannot receive bindings
```
PiperOrigin-RevId: 944313857