Partial and hacky fix for ElaboratedType-related errors.
This really is my best short right now! I tried being cleverer with how each case handles desugaring, but, for example, one problem I think I am running into is that they generally expect to fully desugar all the way past all sugar nodes, but the nodes we're casting are themselves sugar nodes -- so they skip past both the ElaboratedType and the very node they were meant to match. (Where, before, as a special-case, they matched the node because it wasn't nested inside other sugar.)

(Or in other cases I just seriously don't understand why `getAs`/`getAsAdjusted` don't do what I expect, to be honest. Presumably something like "The Canonical type isn't what I expect"...)

This doesn't fix all tests; I do not currently understand why this happens:

```
thread 'test_incomplete_record_has_rs_name' panicked at 'input unexpectedly didn't match the pattern:
expected '"test_namespace_bindings::MyTemplate<test_namespace_bindings::Param>"'
but got '"test_namespace_bindings::MyTemplate<Param>"'
```

It could be that these are coincidental? There are other differences in the AST: https://godbolt.org/z/WsvKjzG6Y (e.g. `TemplateSpecializationType 'MyTemplate<Type>' sugar MyTemplate` vs `TemplateSpecializationType 'MyTemplate<ns::Type>' sugar MyTemplate`.) I'd need to dig more.

But for now, at least opting for fixing a subset of tests and getting help fixing the rest... My brain tired.

PiperOrigin-RevId: 465531292