OSS build: Fixing Bazel-level `cc_bindings_from_rs` problems.
This CL focuses on letting the following build command progress
beyond Bazel problems:

    $ bazel build cc_bindings_from_rs:cc_bindings_from_rs

This CL fixes the following problems:

* Need to declare `clap` and `either` dependencies in `crubit/WORKSPACE`
* Need to use Bazel form of `sh_binary` and `rust_binary`

After this CL, `cc_bindings_from_rs` still can't be built, but it
at least invokes the Rust compiler.  Example of a remaining problem:

* `extern crate rustc_driver;`: `error[E0463]: can't find crate for
  `rustc_driver``

PiperOrigin-RevId: 523991358