Cargo: get the tests running/runnable, even if they do not yet pass.
The main blocker was adding dev-dependencies, which is what the CL chain led to, but there's actually a number of minor issues along the way.

Current status:

```
$ cargo test --workspace --exclude 'rs_bindings_from_cc*' --exclude '*_sys' --no-fail-fast
...
error: 4 targets failed:
    `-p cc_bindings_from_rs --bin cc_bindings_from_rs`
    `-p code_gen_utils --lib`
    `-p token_stream_matchers --lib`
    `-p token_stream_printer --lib`

```

**Special implementation notes:**

 *  I added rustc_middle extern crate on advice of the compiler. I do not know what it means, but without it, we get a lot of errors of the form:

    ```
    error: crate `rustc_stable_hash` required to be available in rlib format, but was not found in this form
      |
      = help: try adding `extern crate rustc_driver;` at the top level of this crate
    ```

    I chose to just do what it said instead of trying to debug further. (It wasn't just rustc_stable_hash, but also, for example, crates like `rand`, and so on -- all resolved by adding the `rustc_driver` extern!)

 *  Doc tests are disabled because we don't test them internally either, so they'll just go stale anyway.

PiperOrigin-RevId: 839003082