Regression tests of ABI incompatibility in a `StructFloat`.
The failure of the `test_struct_float` test introduced by this CL shows
that `rs_bindings_from_cc` may accidentally generate Rust structs that
are layout-compatible, but ABI-incompatible with C++ structs.  This is
most likely caused by replacing some struct fields with an opaque blob
of bytes (which may have different ABI classification than the original
fields).

The test is temporarily disabled via `#[ignore]` - one needs to use the
`--include-ignored` cmdline argument to run the test:

```
$ bazel test --test_output=streamed \
    rs_bindings_from_cc/test/struct/abi_class:main \
    --test_arg=test_struct_float \
    --test_arg=--include-ignored
...
thread 'tests::test_struct_float' panicked at 'assertion failed: `(left == right)`
  left: `579.0`,
 right: `-1.5202937e29`', .../test/struct/abi_class/test.rs:15:9
```

PiperOrigin-RevId: 511837116