Make bindings work for `rs_default...StructWithFieldWithNoDefault` test.
This CL adds a new test to `known_traits/default/default.rs` where
`StructWithFieldWithNoDefault` implements `Default` (and therefore gets
a non-trivial, custom default constructor in its C++ bindings), but also
has a non-`Default` field.  The problem is that in C++ all fields need
to be constructed before the body of a custom constructor starts to
execute - this is a problem because for the non-`Default` field, because
we want to defer/delegate initialization of this field to the
`Default::default` thunk.  Before this CL, bindings generated for the
new `StructWithFieldWithNoDefault` would fail to build with the
following error:

```
.../known_traits/default/rs_default_cc_api.h:277:31:error: call to
deleted constructor of
'::rs_default::field_with_no_default::StructWithoutDefault'
  277 | StructWithFieldWithNoDefault::StructWithFieldWithNoDefault() {
      |                               ^
.../known_traits/default/rs_default_cc_api.h:104:3: note:
'StructWithoutDefault' has been explicitly marked deleted here
  104 |   StructWithoutDefault() = delete;
      |   ^
```

This scenario is fixed by wrapping all fields in an anonymous union:
`union { <actual field type> actual_field_name };`.  This way C++ will
not attempt to invoke the default constructor of the field.
(Similarily, the generated bindings will also have more control over
invoking the destructors of the fields, but this won't matter until C++
bindings actually support custom `Drop` / "drop glue" / destructor
types.

According to our current understanding of the System V ABI, wrapping the
fields in an anonymous union shouldn't change the ABI of the aggregate
type which contains the fields.  OTOH, the ABI of aggregate types is
mostly irrelevant, because they are never passed by value across the FFI
boundary (e.g. see `is_c_abi_compatible_by_value` in
`cc_bindings_from_rs/bindings.rs`).

PiperOrigin-RevId: 542879167