Avoid `#[macro_use]` / tighten where `static_assertions` are visible.
The small refactoring in this CL helps prepate for using
`static_assertions` in the generated Rust bindings, without causing the
following build error: error[E0523]: found two different crates with
name `static_assertions` that are not distinguished by differing `-C
metadata`. This will result in symbol conflicts between the two.

Avoiding `#[macro_use]` also seems desirable in general - AFAIU this
attribute is not needed from Rust 2018 onward.

PiperOrigin-RevId: 436589342