Don't attempt to generate bindings for dynamically sized types.
`struct` bindings include static, compile-time assertions about the size
of the `struct` - these assertions don't work for dynamically sized
types:

C++:

```
.../cc_bindings_from_rs/test/structs/structs_cc_api.h:761:17: error:
static assertion failed due to requirement
'4 == __builtin_offsetof(...DynamicallySizedStruct, unsized_field)'
  static_assert(4 == offsetof(DynamicallySizedStruct, unsized_field));
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.../cc_bindings_from_rs/test/structs/structs_cc_api.h:761:19: note:
expression evaluates to '4 == 0'
  static_assert(4 == offsetof(DynamicallySizedStruct, unsized_field));
                ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Rust:

```
 std::mem::size_of::<...DynamicallySizedStruct>()
                        ^^^^^^^^^^^ doesn't have a size known at compile-time
```

Because of the above, this CL starts to skip bindings generation for
unsized types.

PiperOrigin-RevId: 527088152